"""Generate ``template_map.py`` from Hevy's global exercise template catalog.

Hevy workouts carry a language-independent ``exercise_template_id`` for every
exercise. The built-in ``HEVY_TO_GARMIN`` map is keyed on the English exercise
name, so non-English users have to map everything by hand (#173). This script
joins Hevy's global template catalog (id -> English title) with that name map to
produce ``exercise_template_id -> (category, subcategory)``, which resolves in
any language.

Run after Hevy adds new exercises:

    HEVY_API_KEY=<key> python scripts/gen_template_map.py

Verify the committed file still matches ``HEVY_TO_GARMIN`` (no network, no API
key — this is what CI runs):

    python scripts/gen_template_map.py --check

Only NON-custom (global) templates are included, since custom template ids are
per-account and would not generalise.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

import requests

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "src"
OUT = SRC / "hevy2garmin" / "template_map.py"
BASE = os.environ.get("HEVY_API_KEY_URL", "https://api.hevyapp.com/v1")


def fetch_templates(key: str) -> dict[str, str]:
    """Return {template_id: english_title} for all global Hevy templates."""
    headers = {"api-key": key}
    out: dict[str, str] = {}
    page = 1
    while True:
        resp = requests.get(
            f"{BASE}/exercise_templates",
            params={"page": page, "pageSize": 100},
            headers=headers,
            timeout=30,
        )
        resp.raise_for_status()
        data = resp.json()
        for t in data.get("exercise_templates", []):
            if not t.get("is_custom") and t.get("id") and t.get("title"):
                out[t["id"]] = t["title"]
        if page >= data.get("page_count", page):
            break
        page += 1
    return out


def check() -> int:
    """Report entries whose pair no longer matches ``HEVY_TO_GARMIN``.

    ``lookup_exercise`` resolves the English name first, so a stale generated
    entry is invisible to an English-speaking user — but the template id is
    what a non-English workout resolves through, so drift silently gives those
    users the pre-fix pair. Regeneration needs the Hevy API; this check does
    not, because each generated line carries its source title in a comment.

    Only entries whose title is still in the table can be compared. A title
    that has since been renamed or removed is reported separately: nothing can
    verify it, and it keeps whatever pair it was generated with.
    """
    sys.path.insert(0, str(SRC))
    from hevy2garmin.mapper import HEVY_TO_GARMIN

    entry = re.compile(r'^    "(\w+)": \((\d+), (\d+)\),  # (.+)$', re.M)
    drift: list[str] = []
    orphans: list[str] = []
    total = 0
    for tid, cat, sub, title in entry.findall(OUT.read_text()):
        total += 1
        expected = HEVY_TO_GARMIN.get(title)
        if expected is None:
            orphans.append(f"{title} [{tid}]")
        elif expected != (int(cat), int(sub)):
            drift.append(f"  {title} [{tid}]: generated {(int(cat), int(sub))}, table has {expected}")

    print(f"checked {total} generated entries against HEVY_TO_GARMIN")
    if orphans:
        print(f"note: {len(orphans)} entries whose title is no longer in the table "
              f"(cannot be verified): {', '.join(orphans[:5])}"
              + (" ..." if len(orphans) > 5 else ""))
    if drift:
        print(f"\nout of date ({len(drift)}):", file=sys.stderr)
        print("\n".join(drift), file=sys.stderr)
        print("\nRe-run with HEVY_API_KEY set, or update both files together.", file=sys.stderr)
        return 1
    print("up to date")
    return 0


def main() -> int:
    if "--check" in sys.argv[1:]:
        return check()

    key = os.environ.get("HEVY_API_KEY")
    if not key:
        print("Set HEVY_API_KEY", file=sys.stderr)
        return 1

    sys.path.insert(0, str(SRC))
    from hevy2garmin.mapper import HEVY_TO_GARMIN

    templates = fetch_templates(key)
    mapped: dict[str, tuple[int, int]] = {}
    unmatched: list[str] = []
    for tid, title in templates.items():
        if title in HEVY_TO_GARMIN:
            mapped[tid] = HEVY_TO_GARMIN[title]
        else:
            unmatched.append(title)

    lines = [
        '"""Hevy ``exercise_template_id`` -> Garmin ``(category, subcategory)``.',
        "",
        "Auto-generated by ``scripts/gen_template_map.py``. Language-independent:",
        "the template id is the same regardless of the user's Hevy language (#173).",
        "Do not edit by hand; re-run the generator instead.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "TEMPLATE_TO_GARMIN: dict[str, tuple[int, int]] = {",
    ]
    for tid in sorted(mapped, key=lambda t: templates[t].lower()):
        cat, sub = mapped[tid]
        lines.append(f'    "{tid}": ({cat}, {sub}),  # {templates[tid]}')
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n")

    print(f"global templates: {len(templates)}, mapped: {len(mapped)}, unmatched: {len(unmatched)}")
    print("wrote", OUT.relative_to(REPO))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
